export const options = [
  { label: "JavaScript", value: "JavaScript" },
  { label: "React", value: "React" },
  { label: "Vue", value: "Vue" },
  { label: "Svelte", value: "Svelte" },
  { label: "Angular", value: "Angular" },
  { label: "Next.js", value: "Next.js" },
  { label: "Node.js", value: "Node.js" },
  { label: "Express", value: "Express" },
  { label: "MongoDB", value: "MongoDB" },
  { label: "SQL", value: "SQL" },
  { label: "Python", value: "Python" },
  { label: "Django", value: "Django" },
  { label: "Flask", value: "Flask" },
  { label: "Java", value: "Java" },
  { label: "Spring Boot", value: "Spring Boot" },
  { label: "HTML", value: "HTML" },
  { label: "CSS", value: "CSS" },
  { label: "Tailwind CSS", value: "Tailwind CSS" },
  { label: "Bootstrap", value: "Bootstrap" },
  { label: "Web Development", value: "Web Development" },
  { label: "Frontend", value: "Frontend" },
  { label: "Backend", value: "Backend" },
  { label: "Full Stack", value: "Full Stack" },
  { label: "DevOps", value: "DevOps" },
  { label: "Git", value: "Git" },
  { label: "GitHub", value: "GitHub" },
  { label: "Linux", value: "Linux" },
  { label: "Testing", value: "Testing" },
  { label: "VS Code", value: "VS Code" },
  { label: "Tips & Tricks", value: "Tips & Tricks" },
  { label: "Career", value: "Career" },
];

export const professionOptions = [
  { label: "Software Engineer", value: "Software Engineer" },
  { label: "Frontend Developer", value: "Frontend Developer" },
  { label: "Backend Developer", value: "Backend Developer" },
  { label: "Full Stack Developer", value: "Full Stack Developer" },
  { label: "DevOps Engineer", value: "DevOps Engineer" },
  { label: "UI/UX Designer", value: "UI/UX Designer" },
  { label: "Product Manager", value: "Product Manager" },
  { label: "Data Scientist", value: "Data Scientist" },
  { label: "Machine Learning Engineer", value: "Machine Learning Engineer" },
  { label: "AI Researcher", value: "AI Researcher" },
  { label: "Mobile Developer", value: "Mobile Developer" },
  { label: "Game Developer", value: "Game Developer" },
  { label: "Cybersecurity Specialist", value: "Cybersecurity Specialist" },
  { label: "QA Engineer", value: "QA Engineer" },
  { label: "Cloud Architect", value: "Cloud Architect" },
  { label: "Blockchain Developer", value: "Blockchain Developer" },
  { label: "System Administrator", value: "System Administrator" },
  { label: "Technical Writer", value: "Technical Writer" },
  { label: "IT Support Specialist", value: "IT Support Specialist" },
  { label: "Database Administrator", value: "Database Administrator" },
  { label: "Network Engineer", value: "Network Engineer" },
  { label: "Business Analyst", value: "Business Analyst" },
  { label: "Solutions Architect", value: "Solutions Architect" },
  { label: "Engineering Manager", value: "Engineering Manager" },
  { label: "Tech Lead", value: "Tech Lead" },
  { label: "Freelancer", value: "Freelancer" },
  { label: "Student", value: "Student" },
  { label: "Educator", value: "Educator" },
  { label: "Entrepreneur", value: "Entrepreneur" },
  { label: "Other", value: "Other" },
]
